### ISSUE TITLE
Not Defined

### ISSUE THREAD

**Issue by 32teeth** [JefferyHus/v-odometer#6]
```
[Vue warn]: Error in mounted hook: "ReferenceError: Odometer is not defined
```

**Comment by JefferyHus** [comment]
If you are getting the error of "Unknown Odometer keyword", this means that you are missing odometer library in your application, simply because the Odometer library is not yet exported as an AMD module and still only a commenJS file (refer to: AMD exporting issues). However if you are not building your applciation in a webpack envirment or similar, and you include VueJS file from a public cdn, then you are fine to include the ./v-odometer/dist/main.prod.js, the Vue will be public in your window there for this component will be automatically integrated as a global component and you can simply use it directly insidde your html file:

```xml
	...
	<vue-odometer :value="myValue"></vue-odometer>
	...
```

**Comment by JefferyHus** [comment]
@32teeth are you still having the issue?

**Comment by 32teeth** [comment]
you can close this. my work around was using the odometer npm

**Comment by JefferyHus** [comment]
you need the odometer library as they don't have an AMD module
